apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: default
  labels:
    app: customer-deployment
spec:
  selector:
    matchLabels:
      app: customer-deployment
  template:
    metadata:
      labels:
        app: customer-deployment
    spec:
      containers:
        - name: customer-service
          image: canersir/customer-application
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
  labels:
    app: customer-service
spec:
  selector:
    app: customer-deployment
  ports:
    - name: customer-service-port
      protocol: TCP
      port: 8082
  type: LoadBalancer
  loadBalancerIP: ""